- job:
    name: jjb-tox-cross-python-jenkins
    description: Tests compatibility with master branch of python-jenkins
    parent: tox-py27
    required-projects:
      - jjb/python-jenkins
      - jjb/jenkins-job-builder
    voting: true

- job:
    name: jjb-tox-docs-linkcheck
    parent: tox
    vars:
      tox_envlist: docs-linkcheck

- project:
    templates:
      - docs-on-readthedocs
      - openstack-python-jobs-no-constraints
      - openstack-python35-jobs-no-constraints
      - openstack-python36-jobs-no-constraints
      - openstack-python37-jobs-no-constraints
      - openstack-python38-jobs-no-constraints
    vars:
      rtd_webhook_id: '47271'
    check:
      jobs:
        - jjb-tox-cross-python-jenkins
        - jjb-tox-docs-linkcheck
        - tox-cover
