- job:
    name: jjb-tox-cross-python-jenkins
    description: Tests compatibility with master branch of python-jenkins
    parent: tox-py27
    required-projects:
      - jjb/python-jenkins
      - jjb/jenkins-job-builder
    voting: true

- project:
    check:
      jobs:
        - jjb-tox-cross-python-jenkins
